on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: 'Environment to Deploy to'
        required: true
        type: choice
        options:
          - dev
          - prod
          - test

jobs:
  deploy:
    environment: ${{ github.event.inputs.environment-name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      - name: 'Install dependencies'
        run: flutter pub get
      #       - run: flutter test
        working-directory: app
      - name: 'Build Web Distribution'
        run: flutter build web
        working-directory: app
      - name: 'Publish To Cloudflare Pages'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'simple-math-tester'
          directory: 'build/web'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        working-directory: app